spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sally
    username: sally
    password: sally
  mail:
    host: smtp.gmail.com
    port: 587
    username: soportesally2017@gmail.com
    password: sally123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
